---
- name: ansibleprac
  hosts: webserver
  become: yes
  gather_facts: false
  roles:
    - myrole
    
  
    
    #- name: changing file permissions
      #file:
         #path: "{{location[0]}}"
         #mode: '0664'
    #- debug: var=location

    #- name: creating directory
      #command: mkdir "{{location[1]}}" creates="{{ location[1] }}"
      #register: result
    #- debug: msg="{{ result }}"

    #- name: copying directory
      #ansible.builtin.copy:
        #src: "{{ location2 }}"
        #dest: "{{ location[1] }}"
        #remote_src: yes

    #- name: Install nginx
      #package:
        #name: nginx
        #state: present
        #use: apt
      #notify: start nginx
      #ignore_errors: yes

    #- name: "create www directory"
      #file:
        #path: /var/www/{{ domain }}
        #state: directory
        #mode: '0775'
        #owner: "{{ ansible_user }}"
        #group: "{{ ansible_user }}"


    #- name: delete default nginx site
      #file:
        #path: /etc/nginx/sites-enabled/default
        #state: absent
      #notify: restart nginx

    #- name: copy nginx site.conf
      #template:
        #src: site.conf.j2
        #dest: /etc/nginx/sites-enabled/{{ domain }}
        #owner: root
        #group: root
        #mode: '0644'
      #notify: restart nginx

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
    